from modules import PRIMARY_COLOR_DEFINE,Display_Color
HELP_DOUCUMENT="THASDGADGGGGGGGGGGG-GASDGASDDDDDDDDDDDD-TESTETSTTEST"
def READ_HELP_DOUCUMENTS():
    print("--- Dir8urp Help Doucumention v0.1 alpha ---\n"+Display_Color.SUCCESS(PRIMARY_COLOR_DEFINE,HELP_DOUCUMENT))

#READ_HELP_DOUCUMENTS()